apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend  
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend-service
          image: backend-service:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
  